Des 150 update the register view with the new user information format
generaciondesafiante/Regresemos_a_nuestra_casa_UI pull request #38
Opened 2023-07-05 16:31 UTC by Daniielmayo

2023-07-05 16:57 UTC, DanielCalleCO requested changes

2023-07-05 16:57 UTC, DanielCalleCO commented on .env
> +REACT_APP_API_URL=http://localhost:8080/api
Is this uncommented line necessary? I mean, the 1st line was uncommented and now is commented, and the 2nd line now is uncommented and in develop is commented... Is it an error you skipped, or do you need this file as it is now?

2023-07-05 18:52 UTC, Daniielmayo commented on .env
> +REACT_APP_API_URL=http://localhost:8080/api
Dani for now, yes, since when you make the request to the environment variable in localhost it is easier for the work team to do the reconstruction, I am going to find another way to do it and I will share with you

2023-07-05 18:55 UTC, Daniielmayo commented on src/components/organims/Profile/Profile.jsx
>            <h3 className="profile-info_title"> correo electrónico </h3>
corrected

2023-07-05 18:56 UTC, Daniielmayo commented on src/hooks/useAuthStore.js
> +      // console.log(data);
corrected

2023-07-05 18:56 UTC, Daniielmayo commented on src/store/auth/authSlice.js
> +      console.log(state.user);
corrected

2023-07-05 18:56 UTC, Daniielmayo commented on .env
> +REACT_APP_API_URL=http://localhost:8080/api
Dani for now, yes, since when you make the request to the environment variable in localhost it is easier for the work team to do the reconstruction, I am going to find another way to do it and I will share with you

2023-07-05 19:29 UTC, DanielCalleCO approved these changes

2023-07-06 11:47 UTC, abdulflorez approved these changes

2023-07-07 02:23 UTC, merged