Des 127 update UI backend and db to receive and display new data LOGIN
generaciondesafiante/Regresemos_a_nuestra_casa_UI pull request #41
Opened 2023-07-11 17:25 UTC by Daniielmayo

2023-07-11 18:42 UTC, DanielCalleCO commented on package.json
> +    "fix-format": "npm run pretty:fix && npm run lint:fix"
I think this change was made before by @SthefaniaEcheverry, but anyone deleted it later… Be careful when you review changes in the future to avoid this.

2023-07-11 18:46 UTC, DanielCalleCO requested changes
Awesome job!

2023-07-11 18:46 UTC, DanielCalleCO commented on src/components/organims/Profile/Profile.jsx
> +          <h3 className="profile-info_title">Pais</h3>
```suggestion
          <h3 className="profile-info_title">País</h3>
```

2023-07-11 18:46 UTC, DanielCalleCO commented on src/components/organims/Profile/Profile.jsx
> +          <h3 className="profile-info_title">Telefono</h3>
```suggestion
          <h3 className="profile-info_title">Teléfono</h3>
```

2023-07-11 23:38 UTC, Daniielmayo commented on package.json
> +    "fix-format": "npm run pretty:fix && npm run lint:fix"
Yes Dany already corrected it, I'm sorry, I hadn't done the develop pull

2023-07-11 23:39 UTC, Daniielmayo commented on src/components/organims/Profile/Profile.jsx
> +          <h3 className="profile-info_title">Pais</h3>
FIXED

2023-07-11 23:39 UTC, Daniielmayo commented on src/components/organims/Profile/Profile.jsx
> +          <h3 className="profile-info_title">Telefono</h3>
FIXED

2023-07-12 13:04 UTC, cristianarce89 approved these changes

2023-07-12 13:13 UTC, DanielCalleCO approved these changes
Perfect!

2023-07-12 14:19 UTC, merged