Des 137 make the image profile editable
generaciondesafiante/Regresemos_a_nuestra_casa_UI pull request #64
Opened 2023-09-15 14:48 UTC by cristianarce89

2023-09-15 15:04 UTC, Daniielmayo commented on .env
change the environment variable, don't leave it on localhost

2023-09-15 15:08 UTC, Daniielmayo commented on src/auth/registerPageNavbar/ResgisterPageNavbar.jsx
> +            isRequire={true}
The telephone number should not be required in the registration, it must be false

2023-09-15 15:12 UTC, Daniielmayo commented on src/components/organims/Profile/Profile.css
> +/* .modalEditProfile-circleWrapper {
These comments are necessary, if not, please delete them.

2023-09-15 15:14 UTC, Daniielmayo requested changes

2023-09-15 15:14 UTC, Daniielmayo commented on .env
> +# REACT_APP_API_URL=https://regresemos-cms.herokuapp.com/api
don't leave localhost

2023-09-18 14:52 UTC, Daniielmayo approved these changes

2023-09-18 14:57 UTC, abdulflorez approved these changes

2023-09-18 14:57 UTC, merged