Des 176 exit password change
generaciondesafiante/Regresemos_a_nuestra_casa_UI pull request #70
Opened 2023-09-22 15:49 UTC by Daniielmayo

2023-09-22 19:33 UTC, DanielCalleCO requested changes

2023-09-26 14:10 UTC, Daniielmayo commented on src/components/organims/ChangePasswordProfile/ChangePasswordProfile.css
> +  border: solid 1px #f44336;
resolved

2023-09-26 14:10 UTC, Daniielmayo commented on src/components/organims/ChangePasswordProfile/ChangePasswordProfile.css
> +  border: solid 1px var(--turquoise);
resolved

2023-09-26 14:13 UTC, cristianarce89 approved these changes

2023-09-26 14:23 UTC, DanielCalleCO approved these changes

2023-09-26 14:46 UTC, merged