Des 177 sidebar error in styles for navigation option selected
generaciondesafiante/Regresemos_a_nuestra_casa_UI pull request #72
Opened 2023-09-27 21:21 UTC by Daniielmayo

2023-09-27 21:51 UTC, DanielCalleCO requested changes

2023-09-27 21:51 UTC, DanielCalleCO commented on src/components/molecules/Sidebar/Sidebar.jsx
> +  // Verificar si el usuario está autenticado
translate

2023-09-27 21:51 UTC, DanielCalleCO commented on src/components/molecules/Sidebar/Sidebar.jsx
> +    return null; // No mostrar Sidebar si no está autenticado
translate the comment

2023-09-28 01:06 UTC, DanielCalleCO approved these changes

2023-09-28 13:08 UTC, abdulflorez approved these changes
Buen trabajo!

2023-09-28 13:15 UTC, merged